version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: furia-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: furia-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/furia-fans
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: furia-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo_data:
